version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: bun
  directory: '/frontend'
  target-branch: "main"
  schedule:
    interval: "daily"
  reviewers:
    - Smaug6739
  assignees:
    - Smaug6739
- package-ecosystem: gomod
  directory: '/backend'
  target-branch: "main"
  schedule:
    interval: "daily"
  reviewers:
    - Smaug6739
  assignees:
    - Smaug6739
