services:
  # Alexandrie Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: alexandrie-frontend
    restart: unless-stopped
    user: '${UID}:${GID}'
    volumes:
      - ./frontend:/app # montage du code local
      - /app/node_modules
    ports:
      - '8200:8200'
