services:
  # Alexandrie Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: alexandrie-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app # montage du code local
      - nuxt_build:/app/.nuxt
      - deps:/app/node_modules
    ports:
      - '8200:8200'
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      CHOKIDAR_INTERVAL: 100
volumes:
  nuxt_build:
  deps:
