name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to VPS
        run: |
          echo -e "${DEPLOY_SSH_KEY}" >__TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          scp -o StrictHostKeyChecking=no -v -i __TEMP_INPUT_KEY_FILE -P "${INPUT_PORT}" -r frontend/* smaug@"${INPUT_HOST}":"${INPUT_REMOTE}"
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          INPUT_HOST: ${{ secrets.SSH_HOST }}
          INPUT_REMOTE: /home/smaug/sites/alexandrie
          INPUT_PORT: 22
