name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      INPUT_HOST: ${{ secrets.SSH_HOST }}
      INPUT_REMOTE: /home/smaug/sites/alexandrie
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: |
          cd frontend
          bun install
          cd ../dashboard
          bun install
          cd ../backend
          bun install

      - name: Build frontend
        run: |
          cd frontend
          bun run build

      - name: Build dashboard
        run: |
          cd dashboard
          bun run build

      - name: Build backend
        run: |
          cd backend
          bun run build

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 "${INPUT_HOST}" >> ~/.ssh/known_hosts

          echo -e "${DEPLOY_SSH_KEY}" > deploy_key
          chmod 600 deploy_key
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Create Archives
        run: |
          tar -czf frontend.tar.gz frontend/.output frontend/.env.production
          tar -czf dashboard.tar.gz dashboard/.output dashboard/.env.production
          tar -czf backend.tar.gz backend/dist backend/package.json backend/package-lock.json

      - name: Transfer Archives
        run: |
          scp -i deploy_key ecosystem.config.js ${SSH_USER}@"${INPUT_HOST}":"${INPUT_REMOTE}"
          scp -i deploy_key frontend.tar.gz ${SSH_USER}@"${INPUT_HOST}":"${INPUT_REMOTE}"
          scp -i deploy_key dashboard.tar.gz ${SSH_USER}@"${INPUT_HOST}":"${INPUT_REMOTE}"
          scp -i deploy_key backend.tar.gz ${SSH_USER}@"${INPUT_HOST}":"${INPUT_REMOTE}"
      - name: Extract Archives on Remote
        run: |
          ssh -i deploy_key ${SSH_USER}@"${INPUT_HOST}" "cd ${INPUT_REMOTE} && tar -xzf frontend.tar.gz && tar -xzf dashboard.tar.gz && tar -xzf backend.tar.gz && rm frontend.tar.gz dashboard.tar.gz backend.tar.gz"
      - name: Install dependencies for backend
        run: |
          ssh -i deploy_key ${SSH_USER}@"${INPUT_HOST}" "source ~/.bashrc && cd ${INPUT_REMOTE} && cd backend && bun install --production"
      - name: Start application
        run: |
          ssh -i deploy_key ${SSH_USER}@"${INPUT_HOST}" "cd ${INPUT_REMOTE} && NODE_ENV='production' DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' DATABASE_USER='${{ secrets.DATABASE_USER }}' JWT_SECRET='${{ secrets.JWT_SECRET }}' pm2 start ecosystem.config.js --update-env"
        env:
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
