name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to VPS
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY_BASE64 }}" | base64 -d > deploy_key
          chmod 600 deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 161.97.81.3 >> ~/.ssh/known_hosts
          scp -i deploy_key -r frontend/* 161.97.81.3:/home/smaug/sites/alexandrie/frontend
          scp -i deploy_key -r dashboard/* 161.97.81.3:/home/smaug/sites/alexandrie/dashboard
          scp -i deploy_key -r backend/* 161.97.81.3:/home/smaug/sites/alexandrie/backend
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
