name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../dashboard
          npm install
          cd ../backend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build dashboard
        run: |
          cd dashboard
          npm run build

      - name: Build backend
        run: |
          cd backend
          npm run build
      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          scp -i deploy_key -r --exclude=src frontend/dist/* user@your_server_ip:/var/www/mywebsite/frontend
          scp -i deploy_key -r --exclude=src dashboard/dist/* user@your_server_ip:/var/www/mywebsite/frontend
          scp -i deploy_key -r --exclude=src backend/dist/* user@your_server_ip:/var/www/mywebsite/frontend
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
