name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          export DEPLOY_SSH_KEY="${{ secrets.DEPLOY_SSH_KEY }}"
          export SSH_HOST="$SSH_HOST"
      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_SSH_KEY" > deploy_key
          chmod 644 deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts
          scp -i deploy_key -r frontend/* $SSH_HOST:/home/smaug/sites/alexandrie/frontend
          scp -i deploy_key -r dashboard/* $SSH_HOST:/home/smaug/sites/alexandrie/dashboard
          scp -i deploy_key -r backend/* $SSH_HOST:/home/smaug/sites/alexandrie/backend
