name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Add VPS host key to known_hosts
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.ssh_host }} >> ~/.ssh/known_hosts
      - name: Create deploy key file
        run: echo "$DEPLOY_KEY" > deploy_key
      - name: Set permissions on deploy key
        run: chmod 400 deploy_key
      - name: Check for deploy key file
        run: |
          if [[ ! -f deploy_key ]]; then
            echo "Deploy key file does not exist."
            exit 1
          fi
      - name: Check deploy key file
        run: |
          if ! [[ -f deploy_key ]]; then
            echo "Deploy key file does not exist."
            exit 1
          fi
          if [[ ! -r deploy_key ]]; then
            echo "Deploy key file is not readable."
            exit 1
          fi
          file deploy_key | grep "PEM RSA private key"

      - name: Add deploy key to authorized_keys
        run: echo "$DEPLOY_KEY" >> ~/.ssh/authorized_keys
      - name: Deploy to VPS
        run: scp -i deploy_key -r frontend/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/frontend
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
