name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          scp -i deploy_key -r  frontend/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/frontend
          scp -i deploy_key -r  dashboard/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/dashboard
          scp -i deploy_key -r  backend/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/backend
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
