name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      INPUT_HOST: ${{ secrets.SSH_HOST }}
      INPUT_REMOTE: /home/smaug/sites/alexandrie
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 "${INPUT_HOST}" >> ~/.ssh/known_hosts

          echo -e "${DEPLOY_SSH_KEY}" > deploy_key
          chmod 600 deploy_key
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Create Archives
        run: |
          tar -czf frontend.tar.gz frontend
          tar -czf dashboard.tar.gz dashboard
          tar -czf backend.tar.gz backend

      - name: Transfer Archives
        run: |
          scp -i deploy_key frontend.tar.gz "${SSH_USER}"@"${INPUT_HOST}":"${INPUT_REMOTE}"
          scp -i deploy_key dashboard.tar.gz "${SSH_USER}"@"${INPUT_HOST}":"${INPUT_REMOTE}"
          scp -i deploy_key backend.tar.gz "${SSH_USER}"@"${INPUT_HOST}":"${INPUT_REMOTE}"

      - name: Extract Archives on Remote
        run: |
          ssh -i deploy_key "${SSH_USER}"@"${INPUT_HOST}" "cd ${INPUT_REMOTE} && tar -xzf frontend.tar.gz && tar -xzf dashboard.tar.gz && tar -xzf backend.tar.gz && rm frontend.tar.gz dashboard.tar.gz backend.tar.gz"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
