name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_SSH_KEY" > deploy_key
          chmod 644 deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -t ed25519 161.97.81.3 >> ~/.ssh/known_hosts
          ssh -i deploy_key 161.97.81.3
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
