name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: frontend/*
          host: ${{ secrets.SSH_HOST }}
          remote: /home/smaug/sites/alexandrie
          port: 22
          user: smaug
          key: ${{ secrets.DEPLOY_SSH_KEY }}
