name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../dashboard
          npm install
          cd ../backend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Build dashboard
        run: |
          cd dashboard
          npm run build

      - name: Build backend
        run: |
          cd backend
          npm run build
      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          scp -i ${{ secrets.DEPLOY_SSH_KEY }} -r frontend/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/frontend
          scp -i ${{ secrets.DEPLOY_SSH_KEY }} -r dashboard/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/dashboard
          scp -i ${{ secrets.DEPLOY_SSH_KEY }} -r backend/* ${{ secrets.ssh_host }}:/home/smaug/sites/alexandrie/backend
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
