name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS
        run: |
          echo "$DEPLOY_KEY" > deploy_key
          ssh-keyscan -t rsa ${{secrets.ssh_host}} >> ~/.ssh/known_hosts
          rsync -e "ssh -i deploy_key" -avz frontend/ ${{secrets.ssh_host}}:~/sites/alexandrie/frontend

        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
