name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to VPS
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{secrets.ssh_host}} >> ~/.ssh/known_hosts
          chmod 600 deploy_key
          scp -i deploy_key -r frontend/dist/* smaug@${{secrets.ssh_host}}:~/sites/alexandrie/frontend
          scp -i deploy_key -r dashboard/dist/* smaug@${{secrets.ssh_host}}:~/sites/alexandrie/dashboard
          scp -i deploy_key -r backend/dist/* smaug@${{secrets.ssh_host}}:~/sites/alexandrie/backend
