name: Build & deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/known_hosts
          ssh-keyscan -t ed25519 "${INPUT_HOST}" >> ~/.ssh/known_hosts

          echo -e "${DEPLOY_SSH_KEY}" > deploy_key
          chmod 600 deploy_key
          scp -i deploy_key -r frontend/* "${INPUT_HOST}":"${INPUT_REMOTE}"
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          INPUT_HOST: ${{ secrets.SSH_HOST }}
          INPUT_REMOTE: /home/smaug/sites/alexandrie
          INPUT_PORT: 22
